name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
      - uses: ohpensource/platform-cicd/actions/git/generate-version-and-release-notes@4.0.0.0
        name: semver & changelog
        with:
          user-email: "github-actions@github.com"
          user-name: "github-actions"
          version-prefix: "v"
